Добавил поддержку параметров для эмоджи
tamtam-chat/message-editor pull request #24
Opened 2023-11-29 11:40 UTC by rvrhiv

2023-11-29 11:44 UTC, rvrhiv commented on src/editor/index.ts
> +    replaceOnEmoji(from: number, to: number, emoji: string, params?: EmojiParams): Model {
@sergeche нужно ли тут проверить, что в `emoji: string` содержится только эмоджи без других символов?
Я тестировал, и этот метод отрабатывает нормально, когда передаем просто текст (например `"123"`), текст + эмоджи (`"123😀"`), несколько эмоджи (`"😀😀"`, тогда параметры применятся ко всем переданным эмоджи)

2023-11-29 11:47 UTC, rvrhiv commented
- Нужно ли добавить тесты для этой фичи?
- Нужно ли дописать `README.md`?

2023-11-29 15:16 UTC, sergeche requested changes
В целом получилось несколько разных методов, которые делают одни и те же изменения, но в разных местах и с разным контрактом. Хотя по сути всё сводится к одной простой задаче: для эмоджи, который находится в позиции `pos`, нужно указать объект с параметрами. Я бы сделал одну функцию на решение этой задачи. Что-то типа такого: 

```ts
interface EmojiUpdatePayload {
	/** Позиция эмоджи относительно всей строки */
	pos: number;
	/** Данные, которые нужно добавить. Если `null` — удалить данные */
	data: EmojiData | null;
	/** 
	 * Эмоджи-подсказка. Если указано, то сначала проверим, что эмоджи в модели
	 * совпадает с переданным. Если не совпадает — ничего не меняем
	 */
	hint?: string;
}

function updateEmojiData(tokens: Token[], payload: EmojiUpdatePayload[]): Token[] {
	// 1. Убедимся, что payloads отсортирован
	// 2. Для каждого элемент из payload находим токен и эмоджи в нём
	// 3. Если есть hint, убедимся, что эмоджи совпадают
	// 4. Если всё нашли и надо менять — обновляем токен
}
```

И в API редактора не делать отдельный метод для вставки эмоджи, а делать метод именно для изменения данных в эмоджи. И ты на стороне UI будешь выполнять две операции: вставлять/заменять текст и добавлять кастомные данные для эмоджи

2023-11-29 15:16 UTC, sergeche commented on src/editor/update.ts
> +        token = {
Делаешь деструктуризацию независимо от того, есть эмоджи в токене или нет. Лучше всё-таки проверить сначала, нужно ли вносить изменения

2023-11-29 15:16 UTC, sergeche commented on src/editor/update.ts
> +        token = {
И почему замена только в `midTokens`? Разве в `startTokens` и `endTokens` этого делать не надо?

2023-11-30 17:12 UTC, rvrhiv commented on src/editor/update.ts
> +        token = {
> И почему замена только в `midTokens`? Разве в `startTokens` и `endTokens` этого делать не надо?

`midTokens` это как раз нужные токены из всего массива токенов `tokens` к которым нужно применить форматирование из `format`-токена

2023-12-06 08:35 UTC, sergeche approved these changes
Да, теперь похоже на правду. Вроде всё хорошо

2023-12-06 08:36 UTC, merged

2023-12-06 08:39 UTC, sergeche commented
@tamtam-chat/message-editor@0.10.0